
workflows:
  ios-workflow:
    name: Build vxkit
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Nettoyage et Régénération du projet
        script: |
          rm -rf ios
          flutter create --platforms ios .
          flutter clean
          flutter packages pub get
      - name: Compilation brute iOS (Release)
        script: | 
          # On compile en mode 'ios' simple au lieu de 'ipa' pour éviter l'erreur de signature
          flutter build ios --release --no-codesign
      - name: Création du package IPA pour Sideloadly
        script: | 
          # On se place dans le dossier de sortie de la compilation brute
          cd build/ios/iphoneos
          
          # On crée la structure Payload requise pour le format IPA
          mkdir -p Payload
          cp -r Runner.app Payload/
          
          # On compresse en .ipa directement vers la racine de Codemagic
          zip -r $CM_BUILD_DIR/vxkit.ipa Payload
    artifacts:
      - "*.ipa"