workflows:
  ios-workflow:
    name: Build vxkit
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Nettoyage et Initialisation
        script: |
          rm -rf ios
          flutter create --platforms ios .
          flutter clean
          flutter packages pub get
      - name: Compilation Universelle (No Signature)
        script: | 
          # On compile pour simulateur pour ignorer TOUTE signature Apple
          # Sideloadly se chargera de convertir cela pour votre iPhone
          flutter build ios --debug --simulator
      - name: Packaging pour Sideloadly
        script: | 
          # On cible le dossier Debug-iphonesimulator
          cd build/ios/iphonesimulator
          
          mkdir -p Payload
          cp -r Runner.app Payload/
          
          # On crée l'IPA final
          zip -r $CM_BUILD_DIR/vxkit.ipa Payload
    artifacts:
      - "*.ipa"